#ifndef SCREEN_REFERENCES_H
#define SCREEN_REFERENCES_H

#include <QString>

namespace screen_references {
    static const QString SCREEN_UNKNOWN = "SCREEN_UNKNOWN";
    static const QString DEFAULT_SCREEN = "DEFAULT_SCREEN";
    static const QString SCREEN_LOG_IN = "SCREEN_LOG_IN";
    static const QString SCREEN_CODE_2FA_DIALOG = "SCREEN_CODE_2FA_DIALOG";
    static const QString SCREEN_INPUT_2FA_CODE = "SCREEN_INPUT_2FA_CODE";
    static const QString SCREEN_SAVE_INFO = "SCREEN_SAVE_INFO";
    static const QString SCREEN_FIND_FRIEND = "SCREEN_FIND_FRIEND";
    static const QString SCREEN_REQUEST_ACCESS_LOCATION = "SCREEN_REQUEST_ACCESS_LOCATION";
    static const QString SCREEN_HOME = "SCREEN_HOME";
    static const QString SCREEN_POST = "SCREEN_POST";
    static const QString SCREEN_LOADING_PAGE = "SCREEN_LOADING_PAGE";
    static const QString SCREEN_PAGE = "SCREEN_PAGE";
    static const QString SCREEN_PAGE_MORE_OPTION = "SCREEN_PAGE_MORE_OPTION";
    static const QString SCREEN_PROFILE = "SCREEN_PROFILE";
    static const QString SCREEN_PROFILE_MORE_OPTION = "SCREEN_PROFILE_MORE_OPTION";

    static const QString SCREEN_XPOSED_INSTALLER = "SCREEN_XPOSED_INSTALLER";
    static const QString SCREEN_XPOSED_DIALOG_INSTALL = "SCREEN_XPOSED_DIALOG_INSTALL";
    static const QString SCREEN_XPOSED_INSTALLING = "SCREEN_XPOSED_INSTALLING";
    static const QString SCREEN_REQUEST_ROOT = "SCREEN_REQUEST_ROOT";
    static const QString SCREEN_CODE_EXPIRED = "SCREEN_CODE_EXPIRED";
    static const QString SCREEN_CHECK_POINT = "SCREEN_CHECK_POINT";
    static const QString SCREEN_LOAD_VIETNAMESE_FAILED = "SCREEN_LOAD_VIETNAMESE_FAILED";
    static const QString SCREEN_LOST_INTERNET_CONNECTION = "SCREEN_LOST_INTERNET_CONNECTION";
    static const QString SCREEN_XPOSED_DOWNLOADING = "SCREEN_XPOSED_DOWNLOADING";
    static const QString SCREEN_VIDEO_PLAY_FAILED = "SCREEN_VIDEO_PLAY_FAILED";
    static const QString SCREEN_SESSION_EXPIRED = "SCREEN_SESSION_EXPIRED";
    static const QString SCREEN_LIMITED_FUNCTION = "SCREEN_LIMITED_FUNCTION";
    static const QString SCREEN_CONFIRM_INORGE_FIND_FRIEND = "SCREEN_CONFIRM_INORGE_FIND_FRIEND";
    static const QString SCREEN_POST_LIVE_STREAM = "SCREEN_POST_LIVE_STREAM";
    static const QString SCREEN_FACEBOOK_NOT_RESPONSE = "SCREEN_FACEBOOK_NOT_RESPONSE";
    static const QString SCREEN_SELECT_APP_OPEN = "SCREEN_SELECT_APP_OPEN";
    static const QString SCREEN_LOAD_PAGE_FAILED = "SCREEN_LOAD_PAGE_FAILED";
    static const QString SCREEN_REVIEW_DATA_1 = "SCREEN_REVIEW_DATA_1";
    static const QString SCREEN_REVIEW_DATA_2 = "SCREEN_REVIEW_DATA_2";
    static const QString SCREEN_REVIEW_DATA_3 = "SCREEN_REVIEW_DATA_3";
    static const QString SCREEN_REVIEW_DATA_4 = "SCREEN_REVIEW_DATA_4";
    static const QString SCREEN_REVIEW_DATA_5 = "SCREEN_REVIEW_DATA_5";
    static const QString SCREEN_REVIEW_DATA_DONE = "SCREEN_REVIEW_DATA_DONE";
    static const QString SCREEN_ADD_AVATAR = "SCREEN_ADD_AVATAR";
    static const QString SCREEN_WRONG_PASS = "SCREEN_WRONG_PASS";
    static const QString SCREEN_LOGIN_FAILED = "SCREEN_LOGIN_FAILED";
}

#endif // SCREEN_REFERENCES_H
